### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by Cassolette** [cheeseformice/transformice.js#1]
- [x] Setup workflow for `docusaurus` build and deployment
- [x] Update changelog, remove `(WIP)`

**Comment by Cassolette** [comment]
frontend is a big fat mess 💀

**Comment by Tocutoeltuco** [comment]
i agree
![Screenshot_20220104-103143_Discord-Beta](https://user-images.githubusercontent.com/24902450/148066581-b94e9850-fd2e-4b15-ba49-4b2bc5d0ce27.jpg)
![Screenshot_20220104-103148_Discord-Beta](https://user-images.githubusercontent.com/24902450/148066588-db7a0007-182e-4396-b6e8-481e193c2017.jpg)
